<a href="https://colab.research.google.com/github/janegreira/pruebas_datos/blob/main/Pruebas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [24]:
data = np.random.random((2, 2))
data

array([[0.4553607 , 0.851657  ],
       [0.90840262, 0.16617637]])

In [25]:
data +2 # A cada elemento le sumo 2

array([[2.4553607 , 2.851657  ],
       [2.90840262, 2.16617637]])

In [26]:
data*data # Se multiplica cada elemento por sí mismo

array([[0.20735337, 0.72531965],
       [0.82519533, 0.02761459]])

In [27]:
data@data # Producto matricial

array([[0.98100083, 0.5293364 ],
       [0.56460591, 0.80126204]])